apiVersion: v1
kind: Service
metadata:
  name: interceptor-kedify-proxy-metric-sink
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 9901
    protocol: TCP
    targetPort: 9901
  - name: control-plane
    port: 5678
    protocol: TCP
    targetPort: 5678
